config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "workers#index"

  resources :workers do
    resources :paid_holidays
  end
  resources :paid_holidays do
    collection do
      get :current_month_index
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/paid_holiday.rb
class PaidHoliday < ApplicationRecord
  belongs_to :worker, foreign_key: :used_worker_id
  validates :used_worker_id, presence: true
  validates :first_period, presence: true
  validates :end_period, presence: true
  validates :type, presence: true
  self.inheritance_column = :_type_disabled
  validates :used_days, presence: true
end

app/models/worker.rb
class Worker < ApplicationRecord
  has_many :paid_holiday
  validates :name, presence: true
  validates :hire_date, presence: true
  validates :birth_day, presence: true
  validates :pre_pto, presence: true
  validates :pto, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/paid_holidays_controller.rb
class PaidHolidaysController < ApplicationController
  def index
    @paid_holidays = PaidHoliday.where(used_worker_id: params['worker_id'])
    @worker = Worker.find(params['worker_id'])
  end

  def current_month_index
    current_month = Range.new(Time.zone.today.beginning_of_month, Time.zone.today.end_of_month)
    @current_month_paid_holidays = PaidHoliday.where(first_period: current_month).order(:first_period)
    @worker = Worker.all.order(:id).pluck(:id, :name)
  end

  def new
    @paid_holiday = PaidHoliday.new
    @worker = Worker.find(params['worker_id'])
  end

  def create
    @paid_holiday = PaidHoliday.new(paid_holiday_params)
    @worker = @paid_holiday.build_worker(id: @paid_holiday.used_worker_id)

    if @paid_holiday.save
      redirect_to @paid_holiday
    else
      @worker = Worker.find(paid_holiday_params['used_worker_id'])
      render :new, status: :unprocessable_entity
    end
  end

  private
  def paid_holiday_params
    params.require(:paid_holiday).permit(:used_worker_id, :first_period, :end_period, :type, :used_days, :substitute_worker1, :substitute_worker2)
  end
end

app/controllers/workers_controller.rb
class WorkersController < ApplicationController
  def index
    @workers = Worker.all.decorate
  end

  def show
    @worker = Worker.find(params[:id]).decorate
    @paid_holidays = PaidHoliday.where(used_worker_id: params[:id]).order(:first_period)
  end

  def new
    @worker = Worker.new
  end

  def create
    @worker = Worker.new(worker_params)

    if @worker.save
      redirect_to @worker
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @worker = Worker.find(params[:id])
  end

  def update
    @worker = Worker.find(params[:id])

    if @worker.update(worker_params)
      redirect_to @worker
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @worker = Worker.find(params[:id])
    @paid_holiday = PaidHoliday.where(used_worker_id: params[:id])
    @paid_holiday.destroy_all
    @worker.destroy

    redirect_to root_path, status: :see_other
  end

  private
    def worker_params
      params.require(:worker).permit(:name, :hire_date, :birth_day, :pre_pto, :pto)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/paid_holidays_helper.rb
module PaidHolidaysHelper
end

app/helpers/workers_helper.rb
module WorkersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Attendance</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/paid_holidays/_form.html.slim
= form_with model: paid_holiday do |form|
 div
  = form.hidden_field :used_worker_id, value: @worker.id

 .form-group.col-md-6
  = form.label '休暇開始日時'
  = form.datetime_select :first_period,
                          end_year: Time.zone.now.next_year.year,
                          default: Time.zone.now,
                          start_hour: 4,
                          end_hour: 17,
                          minute_step: 30,
                          class: 'form-control'
  - paid_holiday.errors.full_messages_for(:first_period).each do |message|
    div
     = message

 .form-group.col-md-6
  = form.label '休暇終了日時'
  = form.datetime_select :end_period,
                          end_year: Time.zone.now.next_year.year,
                          default: Time.zone.now,
                          start_hour: 4,
                          end_hour: 17,
                          minute_step: 30,
                          class: 'form-control'
  - paid_holiday.errors.full_messages_for(:end_period).each do |message|
    div
     = message

 .form-group.col-md-6
  = form.label '休暇種別'
  = form.select :type, ['有休',
                        '代休',
                        '半休',
                        '特休',
                        '時間休',
                        '年末年始休'], class: 'form-control'
  - paid_holiday.errors.full_messages_for(:type).each do |message|
    div
     = message

 .form-group.col-md-6
  = form.label '使用日数'
  = form.text_field :used_days, class: 'form-control'
  - paid_holiday.errors.full_messages_for(:used_days).each do |message|
    div
     = message

 .form-group.col-md-6
  = form.label '代勤者１'
  = form.text_field :substitute_worker1, class: 'form-control'
  - paid_holiday.errors.full_messages_for(:substitute_worker1).each do |message|
    div
     = message

 .form-group.col-md-6
  = form.label '代勤者２'
  = form.text_field :substitute_worker2, class: 'form-control'
  - paid_holiday.errors.full_messages_for(:substitute_worker2).each do |message|
    div
     = message

 div
  = form.submit

app/views/paid_holidays/current_month_index.html.slim
h1 当月休暇一覧

= link_to '従業員一覧へ', workers_path, class: 'btn btn-lg btn-dark'

table.table
  tr
    th 休暇者
    th 休暇期間
    th 種別
    th 使用日数
    th 代勤者１
    th 代勤者２
  - @current_month_paid_holidays.each do |paid_holiday|
    tr
      td = @worker[paid_holiday.used_worker_id - 1][1]
      td = paid_holiday.first_period.strftime("%Y/%m/%d %H:%M") + '～' + paid_holiday.end_period.strftime("%Y/%m/%d %H:%M")
      td = paid_holiday.type
      td = paid_holiday.used_days
      td = paid_holiday.substitute_worker1
      td = paid_holiday.substitute_worker2

app/views/paid_holidays/index.html.slim
h1 休暇一覧

= link_to '休暇登録', new_worker_paid_holiday_path

= @worker.name

= link_to '従業員一覧へ', workers_path

table.table
  tr
    th 開始日
    th 終了日
    th 種別
    th 代勤者１
    th 代勤者２
  - @paid_holidays.each do |paid_holiday|
    tr
      td = paid_holiday.first_period.strftime("%Y/%m/%d %H:%M")
      td = paid_holiday.end_period.strftime("%Y/%m/%d %H:%M")
      td = paid_holiday.type
      td = paid_holiday.substitute_worker1
      td = paid_holiday.substitute_worker2

app/views/paid_holidays/new.html.slim
h1 休暇登録

h3 休暇者
= @worker.name
= render "form", paid_holiday: @paid_holiday

= link_to "従業員詳細へ戻る", worker_path(@worker.id), class: 'btn btn-lg btn-dark'

app/views/workers/_form.html.slim
= form_with model: worker do |form|
 .form-group.col-md-6
  = form.label '名前'
  = form.text_field :name, class: 'form-control'
  - worker.errors.full_messages_for(:name).each do |message|
    div
     = message

 .form-group.col-md-6
  = form.label '雇入れ日時'
  = form.date_field :hire_date, class: 'form-control'
  - worker.errors.full_messages_for(:hire_date).each do |message|
    div
     = message

 .form-group.col-md-6
  = form.label '誕生日'
  = form.date_field :birth_day, class: 'form-control'
  - worker.errors.full_messages_for(:birth_day).each do |message|
    div
     = message

 .form-group.col-md-6
  = form.label '昨年度有休残日数'
  = form.text_field :pre_pto, class: 'form-control'
  - worker.errors.full_messages_for(:pre_pto).each do |message|
    div
     = message

 .form-group.col-md-6
  = form.label '今年度有休残日数'
  = form.text_field :pto, class: 'form-control'
  - worker.errors.full_messages_for(:pto).each do |message|
    div
     = message

 .form-group.col-md-6
  = form.submit

app/views/workers/edit.html.slim
h1 従業員編集

= render "form", worker: @worker

= link_to "従業員一覧へ", root_path, class: 'btn btn-lg btn-dark'

app/views/workers/index.html.slim
= link_to '当月休暇一覧', current_month_index_paid_holidays_path, class: 'btn btn-info'

h1 従業員一覧

= link_to '従業員登録', new_worker_path, class: 'btn btn-sm btn-primary'

table.table
 tr
   th 名前
   th 有休残日数
   th
   th
 - @workers.each do |worker|
   tr
     td = link_to "#{worker.name}", worker_path(worker)
     td = worker.current_pto.to_s + '日'
     td = link_to "編集", edit_worker_path(worker), class: 'btn btn-sm btn-success'
     td = link_to "削除", worker_path(worker), class:'btn btn-sm btn-danger', data:{ turbo_method: :delete, turbo_confirm: "削除してもよろしいでしょうか？"}

app/views/workers/new.html.slim
h1 従業員登録

= render "form", worker: @worker

= link_to "従業員一覧へ", root_path, class: 'btn btn-lg btn-dark'

app/views/workers/show.html.slim
section
  h1 労働者詳細
  p
    span
      = link_to "編集", edit_worker_path(@worker), class: 'btn btn-success'
      = link_to "削除", worker_path(@worker), class:'btn btn-danger', data:{ turbo_method: :delete, turbo_confirm: "削除してもよろしいでしょうか？"}
  table.table
    tr
      th 名前
      th 現在有給残日数
      th 年度初め有休
      th 昨年度有休残日数
      th 今年度有休付与日数
      th 雇入れ日時
      th 勤続年数
    tr
      td = @worker.name + '(' + @worker.age.to_s + '歳)'
      td = @worker.current_pto.to_s + '日'
      td = @worker.all_pto.to_s + '日'
      td = @worker.pre_pto.to_s + '日'
      td = @worker.pto.to_s + '日'
      td = @worker.hire_date.strftime("%Y年%m月%d日")
      td = @worker.seniority.to_s + '年'

= link_to "従業員一覧へ", root_path, class: 'btn btn-lg btn-dark'

section
  h1 休暇一覧

  = link_to '休暇登録', new_worker_paid_holiday_path(@worker.id), class: 'btn btn-secondary'

  table.table
    tr
      th 休暇期間
      th 種別
      th 使用日数
      th 代勤者１
      th 代勤者２
    - @paid_holidays.each do |paid_holiday|
      tr
        td = paid_holiday.first_period.strftime("%Y/%m/%d %H:%M") + '～' + paid_holiday.end_period.strftime("%Y/%m/%d %H:%M")
        td = paid_holiday.type
        td = paid_holiday.used_days
        td = paid_holiday.substitute_worker1
        td = paid_holiday.substitute_worker2